{"name": "Проверка появления номера созданного заказа в разделе \"В работе\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Не удалось найти элемент ['xpath', \".//h1[contains(text(), 'Соберите бургер')]\"]\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "browser = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"67e5552e-4c8b-4f1c-9f69-a4809a0b6cb5\")>\ncreate_user = ({'email': 'katherine31@example.net', 'name': 'Steven Middleton', 'password': '!miUlOgDU1'}, <Response [403]>)\n\n    @pytest.fixture\n    def login_random_user(browser, create_user):\n        \"\"\"\n        Фикстура для логина в систему с помощью данных созданного пользователя.\n        \"\"\"\n        create_user_data = create_user[0]  # Получение данных созданного пользователя\n        main_page = MainPage(browser, BASE_URL)  # Инициализация страницы с заголовком\n        main_page.click_user_account_button()  # Клик по кнопке \"Личный кабинет\"\n        login_page = LoginPage(browser, LOGIN_URL)  # Инициализация страницы логина\n        login_page.enter_user_data(create_user_data[\"email\"], create_user_data[\"password\"])  # Ввод данных для логина\n>       login_page.click_login_button()\n\nconftest.py:86: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:30: in click_login_button\n    self.find_element(MainPageLocator.TEXT_BURGER)\npages\\base_page.py:34: in find_element\n    return WebDriverWait(self.driver, time).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"67e5552e-4c8b-4f1c-9f69-a4809a0b6cb5\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x000001D6A84BFE20>\nmessage = 'Не удалось найти элемент [\\'xpath\\', \".//h1[contains(text(), \\'Соберите бургер\\')]\"]'\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Не удалось найти элемент ['xpath', \".//h1[contains(text(), 'Соберите бургер')]\"]\nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "description": "Тест проверяет, что после оформления заказа его номер появляется в разделе В работе", "parameters": [{"name": "browser", "value": "'firefox'"}], "start": 1739896380750, "stop": 1739896380750, "uuid": "08e48f40-cd36-4bf7-a5d4-4f2b3973b5a9", "historyId": "fd9dcbc8371b4e91a95be611c3a86fc5", "testCaseId": "d7747efc423636778c3317a10b46dea4", "fullName": "tests.test_feed_page.TestFeedPage#test_order_number_appeared_in_work", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed_page"}, {"name": "subSuite", "value": "TestFeedPage"}, {"name": "host", "value": "DESKTOP-1H286BJ"}, {"name": "thread", "value": "28916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed_page"}]}