{"name": "Проверка появления номера созданного заказа в разделе \"В работе\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: Не удалось найти элемент ['xpath', \".//h1[contains(text(), 'Соберите бургер')]\"]\nStacktrace:\n\tGetHandleVerifier [0x00AF02D3+25139]\n\t(No symbol) [0x00A7B284]\n\t(No symbol) [0x009504A3]\n\t(No symbol) [0x00998338]\n\t(No symbol) [0x0099868B]\n\t(No symbol) [0x009E0F62]\n\t(No symbol) [0x009BCF84]\n\t(No symbol) [0x009DE6E1]\n\t(No symbol) [0x009BCD36]\n\t(No symbol) [0x0098BD29]\n\t(No symbol) [0x0098D064]\n\tGetHandleVerifier [0x00DFB193+3215603]\n\tGetHandleVerifier [0x00E1230A+3310186]\n\tGetHandleVerifier [0x00E0C522+3286146]\n\tGetHandleVerifier [0x00B89CD0+654384]\n\t(No symbol) [0x00A8460D]\n\t(No symbol) [0x00A814F8]\n\t(No symbol) [0x00A81697]\n\t(No symbol) [0x00A73D70]\n\tBaseThreadInitThunk [0x76567BA9+25]\n\tRtlInitializeExceptionChain [0x77A6C28B+107]\n\tRtlClearBits [0x77A6C20F+191]", "trace": "browser = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"f62812fa3542f6c25238de5819f87cf6\")>\ncreate_user = ({'email': 'ubrown@example.net', 'name': 'Kaitlin Evans', 'password': '^k#4ABWm_x'}, <Response [403]>)\n\n    @pytest.fixture\n    def login_random_user(browser, create_user):\n        \"\"\"\n        Фикстура для логина в систему с помощью данных созданного пользователя.\n        \"\"\"\n        create_user_data = create_user[0]  # Получение данных созданного пользователя\n        main_page = MainPage(browser, BASE_URL)  # Инициализация страницы с заголовком\n        main_page.click_user_account_button()  # Клик по кнопке \"Личный кабинет\"\n        login_page = LoginPage(browser, LOGIN_URL)  # Инициализация страницы логина\n        login_page.enter_user_data(create_user_data[\"email\"], create_user_data[\"password\"])  # Ввод данных для логина\n>       login_page.click_login_button()\n\nconftest.py:86: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\npages\\login_page.py:30: in click_login_button\n    self.find_element(MainPageLocator.TEXT_BURGER)\npages\\base_page.py:34: in find_element\n    return WebDriverWait(self.driver, time).until(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"f62812fa3542f6c25238de5819f87cf6\")>, method = <function visibility_of_element_located.<locals>._predicate at 0x000001DB3566C2C0>\nmessage = 'Не удалось найти элемент [\\'xpath\\', \".//h1[contains(text(), \\'Соберите бургер\\')]\"]'\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: Не удалось найти элемент ['xpath', \".//h1[contains(text(), 'Соберите бургер')]\"]\nE       Stacktrace:\nE       \tGetHandleVerifier [0x00AF02D3+25139]\nE       \t(No symbol) [0x00A7B284]\nE       \t(No symbol) [0x009504A3]\nE       \t(No symbol) [0x00998338]\nE       \t(No symbol) [0x0099868B]\nE       \t(No symbol) [0x009E0F62]\nE       \t(No symbol) [0x009BCF84]\nE       \t(No symbol) [0x009DE6E1]\nE       \t(No symbol) [0x009BCD36]\nE       \t(No symbol) [0x0098BD29]\nE       \t(No symbol) [0x0098D064]\nE       \tGetHandleVerifier [0x00DFB193+3215603]\nE       \tGetHandleVerifier [0x00E1230A+3310186]\nE       \tGetHandleVerifier [0x00E0C522+3286146]\nE       \tGetHandleVerifier [0x00B89CD0+654384]\nE       \t(No symbol) [0x00A8460D]\nE       \t(No symbol) [0x00A814F8]\nE       \t(No symbol) [0x00A81697]\nE       \t(No symbol) [0x00A73D70]\nE       \tBaseThreadInitThunk [0x76567BA9+25]\nE       \tRtlInitializeExceptionChain [0x77A6C28B+107]\nE       \tRtlClearBits [0x77A6C20F+191]\n\nD:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "description": "Тест проверяет, что после оформления заказа его номер появляется в разделе В работе", "parameters": [{"name": "browser", "value": "'chrome'"}], "start": 1739853835068, "stop": 1739853835068, "uuid": "7907c13d-81a5-4faa-aa18-462221c8d1c9", "historyId": "ad63ed80f20485313bc5b0438e791b9a", "testCaseId": "d7747efc423636778c3317a10b46dea4", "fullName": "tests.test_feed_page.TestFeedPage#test_order_number_appeared_in_work", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_feed_page"}, {"name": "subSuite", "value": "TestFeedPage"}, {"name": "host", "value": "DESKTOP-1H286BJ"}, {"name": "thread", "value": "28056-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_feed_page"}]}