{"uuid": "e4dff9c7-e870-4162-9911-ebe16f1e5257", "children": ["5129e662-4dff-4a46-b038-b1b710f1c484"], "befores": [{"name": "create_order", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'\n", "trace": "  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\REPO\\Python\\Yandex\\Sunshine\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\REPO\\yandex\\Diplom\\Diplom_3\\conftest.py\", line 96, in create_order\n    token = create_user[1].json()[\"accessToken\"]  # Получение токена пользователя\n            ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^\n"}, "start": 1739894923748, "stop": 1739894923748}], "start": 1739894923748, "stop": 1739894923900}